import localforage from 'https://cdn.skypack.dev/localforage';
import {storage} from './storage.js'
localforage.config({
    driver: [
        localforage.INDEXEDDB,
        localforage.LOCALSTORAGE,
        localforage.WEBSQL
    ],
    name: 'localforage'
});

let openSnpDbUrls = localforage.createInstance({
    name: "openSnpDbUrls",
    storeName: "userUrls"
})
let userTxts = localforage.createInstance({
    name: "userTxts",
    storeName: "userTxts"
})

let userPhenotypes = localforage.createInstance({
    name: "userPhenotypes",
    storeName: "userPhenotypes"
})

let usersByPhenotype = localforage.createInstance({
    name: "usersByPhenotype",
    storeName: "userusersByPhenotypeTxts"
})

const get23 = {}
// get all users with genotype data (23andMe, illumina, ancestry etc)
get23.getAllUsers = async function () { 
    const newLocal = 'usersFull';
    let dt
    dt = await openSnpDbUrls.getItem(newLocal); // check for users in localstorage
    if (dt == null) {
        let url = 'https://corsproxy.io/?https://opensnp.org/users.json'
        let users = (await (await fetch(url)).json())
        let dt2 = users.sort((a, b) => a.id - b.id)
        dt = openSnpDbUrls.setItem('usersFull', dt2)
    }
    return dt
}

get23.getTxts = async function (usersData) {
    console.log("--------------------------")
    console.log("Retreiving OpenSnp users!")
    console.log("getTxts function running, even retreiving from storage is slow.")
    // clearTableUsingKeyLength(table,maxKeys)
    let arr = []
    let urls = (await usersData).map(x => x["genotype.download_url"])

    //remove old txts if table is full
    // let storageList = await table.keys()
    // //console.log("storageList.filter(x => urls.includes(x)",storageList.filter(x => urls.includes(x)))
    storage.clearTableButKeepKeyList(userTxts, urls)

    for (let i = 0; i < urls.length; i++) {
        let parsedUser2 = await userTxts.getItem(urls[i]);
        console.log("processing user #", i)

        if (parsedUser2 == null) {
            console.log("user",i," NOT found in storage")
            let url2 = 'https://corsproxy.io/?' + urls[i]
            const user = (await (await fetch(url2)).text())
            let parsedUser = (await get23.parseTxts(user, usersData[i]))

            console.log(" getTxts parsedUser",parsedUser)
            arr.push(parsedUser)
            userTxts.setItem(urls[i], parsedUser);
        } else {
            console.log("user",i," found in storage");
            arr.push(parsedUser2)
        }
    }
    return arr
}

// create 23andme obj and data 
get23.parseTxts = async function (txt, usersData) {
    let obj = {}
    let rows = txt.split(/[\r\n]+/g)
    // obj.txt = txt
    obj.openSnp = await usersData

    let n = rows.filter(r => (r[0] == '#')).length
    if (n==0){
        obj.meta = false
        obj.cols = rows[n].slice(2).split(/\t/)
    }else {
        obj.meta = rows.slice(0, n - 1).join('\r\n')
        obj.cols = rows[n - 1].slice(2).split(/\t/)
    }
    obj.year = rows[0].split(/\r?\n|\r|\n/g)[0].slice(-4)
    obj.qc = rows[0].substring(0, 37) == '# This data file generated by 23andMe'
    obj.dt = rows.slice(n)
    obj.variant_number = obj.dt.length

    obj.dt = obj.dt.map((r, i) => {
        r = r.split('\t')
        r[2] = parseInt(r[2])
        // position in the chr
        r[4] = i
        return r
    })
    return obj
}

// filter users without 23andme data (type = "23andme")
get23.getUsersByType = async function (type, users) {
    let arr = []
    users.filter(row => row.genotypes.length > 0).map(dt => {

        // keep user with one or more 23andme files
        dt.genotypes.map(i => {
            if (dt.genotypes.length > 0 && i.filetype == type) {
                let innerObj = {};
                innerObj["name"] = dt["name"];
                innerObj["id"] = dt["id"];
                innerObj["genotype.id"] = i.id;
                innerObj["genotype.filetype"] = i.filetype;
                innerObj["genotype.download_url"] = i.download_url.replace("http", "https")
                arr.push(innerObj)
            }
        })
    })
    return arr
}

// get users with a specific phenotype, filter users with 23andme data 
// get23.getUsersByPhenotypeId = async function (phenoId,keysLen) {
//     //console.log("---------------------------")
//     //console.log("running... get23.getUsersByPhenotypeId function")
//     //console.log("phenotype id:", phenoId)
//     let allUsers = await  get23.getAllUsers()
//     const cors = `https://corsproxy.io/?`
//     let onePhenotypeUrl = `https://opensnp.org/phenotypes/json/variations/${phenoId}.json`
//     let users = (await (await fetch(cors + onePhenotypeUrl)).json())
//     let userIds = users.users.map(x => x.user_id)
//     // get users with phenotype data (even those without genotype data)
//     const userIds2 = allUsers.filter(({
//         id
//     }) => userIds.includes(id));
//     let cleanUsers
//     if (userIds2.length < 6) {
//         cleanUsers = await get23.getUsersByType("23andme", userIds2)
//     } else {
//         cleanUsers = (await get23.getUsersByType("23andme", userIds2.slice(6, 19))).slice(0,3)//.slice(4,15))).slice(0,6)
//         //console.log("Warning: user txts for phenotypeID", phenoId, "> 6. First 6 files used.")
//     }
//     // get 23 and me texts from urls using getTxts function
//     let snpTxts = await get23.getTxts(cleanUsers,keysLen,maxKeys)
//     //console.log("User txts for phenotypeID", phenoId, ": ", snpTxts)
//     return snpTxts
// }

get23.getUsersByPhenotypeId = async function (phenoId, keysLen, maxKeys) {

    let allUsers = await get23.getAllUsers()
    const cors = `https://corsproxy.io/?`
    let onePhenotypeUrl = `https://opensnp.org/phenotypes/json/variations/${phenoId}.json`
    let users = await usersByPhenotype.getItem("onePhenotypeUrl")
    // console.log("users ",users )

    if (users == null){
        users = (await (await fetch(cors + onePhenotypeUrl)).json())
        usersByPhenotype.setItem(onePhenotypeUrl,users)
    }
    let userIds = users.users.map(x => x.user_id)
    // console.log("userIds",users)
    // get users with phenotype data (even those without genotype data)
    const userIds2 = allUsers.filter(({
        id
    }) => userIds.includes(id));
    let cleanUsers
    let maxUsers = 3
    if (userIds2.length < maxUsers) {
        cleanUsers =  get23.getUsersByType("23andme", userIds2)
    } else {
        cleanUsers = await (get23.getUsersByType("23andme", userIds2.slice(6, 10)))//.slice(0,maxUsers)
        console.log("Warning: user txts for phenotypeID", phenoId, "> 7. First 6 files used.")
    }
    // get 23 and me texts from urls using getTxts function
    let snpTxts = await get23.getTxts(cleanUsers, keysLen, maxKeys)

    return snpTxts
}
get23.getUserPhenotypes = async function () {
    const allPhenotypesUrl = 'https://opensnp.org/phenotypes.json'
    const allPhenotypes = await userPhenotypes.getItem(allPhenotypesUrl);

    if (allPhenotypes == null) {
        const cors = `https://corsproxy.io/?`
        const allPhenotypes = (await (await fetch(cors + allPhenotypesUrl)).json()).sort((a, b) => b.number_of_users - a.number_of_users)
        userPhenotypes.setItem(allPhenotypesUrl, allPhenotypes);
    }
    // //console.log(allPhenotypes.length," phenotypes found ",allPhenotypes)
    return allPhenotypes
}

get23.getPhenotypeNameFromId = async function (id) {
    //console.log("---------------------------")
    //console.log("running... get23.getPhenotypeNameFromId function")
    const dt = await get23.getUserPhenotypes()
    console.log("dt",dt)
    const name = dt.filter(x => x.id == id)[0].characteristic
    //console.log("Phenotype id", id, "corresponds to:", name)
    return name
}
get23.getPhenotypeIdFromName = async function (characteristic) {
    console.log("---------------------------")
    console.log("running... get23.getPhenotypeNameFromId function")
    const dt = await get23.getUserPhenotypes()
    console.log("dt",dt)
    const id = dt.filter(x => x.characteristic == characteristic)[0].id
    console.log("Phenotype name", id, "corresponds to:", characteristic)
    return id
}

// const id = 3
const keysLen = 5
const maxKeys = 14
// // const storageSize = 1.3
// const td2Users = await get23.getUsersByPhenotypeId(id,keysLen)
// const name = await get23.getPhenotypeNameFromId(id)
// const phenotypes = (await get23.getUserPhenotypes()).sort((a, b) => a.id - b.id)
//console.log("phenotypes",phenotypes)
// const userTableSize = await getLocalForageTableSize(userTxts)

export {get23}